UPDATE products SET image_url = '/uploads/americano.jpeg' WHERE name LIKE '%Americano%';
UPDATE products SET image_url = '/uploads/cafe latte.jpeg' WHERE name LIKE '%Latte%' OR name LIKE '%Espresso%' OR name LIKE '%Mocha%';
UPDATE products SET image_url = '/uploads/cappucino.jpeg' WHERE name LIKE '%Cappuccino%';
UPDATE products SET image_url = '/uploads/matcha.jpeg' WHERE name LIKE '%Matcha%';
UPDATE products SET image_url = '/uploads/chocolate milk.jpeg' WHERE name LIKE '%Chocolate%';
UPDATE products SET image_url = '/uploads/croissant.jpeg' WHERE name LIKE '%Croissant%';
UPDATE products SET image_url = '/uploads/nasi-goreng.jpeg' WHERE name LIKE '%Nasi%';
UPDATE products SET image_url = '/uploads/cheescake.jpeg' WHERE name LIKE '%Cheesecake%';
UPDATE products SET image_url = '/uploads/iced tea.jpeg' WHERE name LIKE '%Tea%';